# Generated by Django 5.0.7 on 2024-08-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='ratings',
            new_name='rating',
        ),
    ]
